# Generated by Django 5.2.5 on 2025-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_order_date_alter_orderline_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Created'), ('p', 'In Progress'), ('f', 'Finished'), ('x', 'Cancelled')], default='c', max_length=1, verbose_name='Status'),
        ),
    ]
